### ISSUE TITLE
LinkWithDropdown cannot be closed programmatically (or I can't find a way to do this, please help)

### ISSUE THREAD

**Issue by valzav** [aruberto/react-foundation-components#14]

**Comment by jcalfee** [comment]
Is programmatically closing necessary?  Are you just wanting the component to close on mouse out or on click of one of its items?

In the code:  The OverlayTrigger is using setting a showHover boolean based on mouse in / out events.  I don't know how this component is suppose to close itself..

**Comment by aruberto** [comment]
LinkWithDropdown (which is just OverlayTrigger) is utility to automatically do all the show/hide plumbing for the most common use cases of click/hover/focus.

If you want to control show/hide logic, shouldn't need OverlayTrigger, just render Dropdown yourself:

```
state = { show: false };

handleToggle = () => this.setState({ show: !this.state.show });

render() {
  return (
    <div>
        <Button onClick={this.handleToggle}>Toggle Controlled</Button>
        {this.state.show && <Dropdown>I'm a dropdown!</Dropdown>}
    </div>
  );
}
```

**Comment by valzav** [comment]
Thank you, I'll try use Dropdown directly.
