### ISSUE TITLE
Issue with global styles

### ISSUE THREAD

**Issue by chrischen** [aruberto/react-foundation-components#18]
lib/global/visibility/index.js

`var _createWrapperComponent = require('../util/create-wrapper-component');`

should be

`var _createWrapperComponent = require('../../util/create-wrapper-component');`

**Comment by henrysxie** [comment]
👍

**Comment by aruberto** [comment]
Believe this should be fixed by #12 

Currently see this when I build:

![image](https://cloud.githubusercontent.com/assets/9933826/18726290/bcd5472a-8011-11e6-93a8-0dbb31b14d46.png)

I will be releasing new version soon.
