### ISSUE TITLE
Unknown Prop warnings in React 15.2

### ISSUE THREAD

**Issue by frankleng** [aruberto/react-foundation-components#19]
@aruberto getting warnings about props being passed into a div.
`<div horizontalAlignment={} />`
Seems like a behavior caused by `createWrapperComponent` when using the flex grid.

Please advise.

**Comment by madc** [comment]
We experience the same warnings. This is related to [Unknown Prop Warning](https://facebook.github.io/react/warnings/unknown-prop.html)

**Comment by rkoberg** [comment]
me too....

**Comment by behivetech** [comment]
It looks like there's several components in this library passing props into regular DOM elements which wasn't being watched in earlier versions of React.

**Comment by valzav** [comment]
@aruberto would you be interested to be working on this for a bounty? Feel free to contact me at valentine.zavgorodnev@gmail.com to discuss.

**Comment by frankleng** [comment]
Thanks @aruberto!

**Comment by valzav** [comment]
@aruberto, thanks for the quick fix!
