### ISSUE TITLE
high severity vulnerability when running npm install --save react-foundation-components

### ISSUE THREAD

**Issue by bileser** [aruberto/react-foundation-components#34]
![bildschirmfoto 2018-08-21 um 10 23 14](https://user-images.githubusercontent.com/12259945/44389990-957de500-a52c-11e8-9984-ca1c868dc693.png)

Where is JQuery used in react-foundation-components? How does JQuery fit with React?

**Comment by aruberto** [comment]
react-foundation-components depends on foundation-sites which depends on jQuery. 

react-foundation-components only uses the SCSS files from foundation-sites package, not any of the Javascript. Since we don't use foundation-sites JS, jQuery isn't actually being used.
